AccountingSoftware/Models/ViewModels/DeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.Models.ViewModels
{
    public class DeleteViewModel
    {
        public Guid Guid { get; set; }

        public string Message { get; set; }
    }
}

AccountingSoftware/Models/ViewModels/TransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.Models.ViewModels
{
    public class TransactionViewModel
    {
        public Guid TransactionGuid { get; set; }

        [Display(Name = "شماره حساب")]
        public string AccountNumber { get; set; }

        [Display(Name = "نوع")]
        public string Type { get; set; }

        [Display(Name = "وضعیت")]
        public string State { get; set; }

        [Display(Name = "مبلغ (تومان)")]
        public long Cost { get; set; }

        [Display(Name = "اعتبار (تومان)")]
        public long Credit { get; set; }

        [Display(Name = "طرف حساب")]
        public string AccountSide { get; set; }

        [Display(Name = "توضیحات")]
        public string Description { get; set; }

        [Display(Name = "تاریخ وصول")]
        public string ReceiptDate { get; set; }

        [Display(Name = "تاریخ آخرین ویرایش")]
        public string ModifiedDate { get; set; }

        [Display(Name = "چک")]
        public bool IsCheckTransaction { get; set; }
    }
}

AccountingSoftware/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingSoftware.Common;
using AccountingSoftware.Models;
using AccountingSoftware.Models.Entities;
using AccountingSoftware.Models.Enums;
using AccountingSoftware.Models.Repositories;
using AccountingSoftware.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AccountingSoftware.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly AccountingSoftwareContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public TransactionsController(AccountingSoftwareContext context,
                UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete)
                .OrderByDescending(x => x.ReceiptDate)
                .Select(x => new TransactionViewModel()
                {
                    TransactionGuid = x.TransactionGuid,
                    AccountNumber = string.IsNullOrEmpty(x.Account.AccountNumber) ? Messages.NotSet : x.Account.AccountNumber,
                    Type = x.TypeCode.DisplayValue,
                    State = x.StateCode.DisplayValue,
                    Cost = x.Cost,
                    Credit = x.Credit,
                    AccountSide = string.IsNullOrEmpty(x.AccountSide) ? Messages.NotSet : x.AccountSide,
                    Description = string.IsNullOrEmpty(x.Description) ? Messages.NotSet : x.Description,
                    IsCheckTransaction = x.IsCheckTransaction,
                    ReceiptDate = PersianDateExtensionMethods.ToPeString(x.ReceiptDate, "yyyy/MM/dd"),
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(transactions);
        }

        [HttpGet]
        public IActionResult CreateAccountTransaction()
        {
            CodesRepository codeRepository = new CodesRepository(context);

            ViewBag.Accounts = new AccountsRepository(context).GetAccounts(userManager.GetUserId(User));
            ViewBag.TransactionTypes = codeRepository.GetCodesByCodeGroupGuid(CodeGroups.TransactionType);
            ViewBag.TransactionStates = codeRepository.GetCodesByCodeGroupGuid(CodeGroups.TransactionState);

            return View();
        }

        [HttpPost]
        public IActionResult CreateAccountTransaction(CreateAccountTransactionViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.AccountGuid = Constants.DefaultAccountGuid;
                long cost = Convert.ToInt64(model.Cost);

                Transaction transaction = new Transaction
                {
                    AccountGuid = model.AccountGuid,
                    TypeCodeGuid = model.TypeGuid,
                    StateCodeGuid = model.StateGuid,
                    Title = model.Title,
                    Cost = cost,
                    AccountSide = model.AccountSide,
                    Description = model.Description,
                    ReceiptDate = PersianDateExtensionMethods.ToGeorgianDateTime(model.ReceiptDate)
                };

                if (model.AccountGuid.HasValue)
                {
                    if (model.StateGuid == Codes.PassedState)
                    {
                        var account = context.Account
                            .Where(x => x.AccountGuid == model.AccountGuid)
                            .SingleOrDefault();

                        if (account == null)
                        {
                            TempData["ToasterState"] = ToasterState.Error;
                            TempData["ToasterType"] = ToasterType.Message;
                            TempData["ToasterMessage"] = Messages.CreateTransactionFailedAccountNotValid;

                            return RedirectToAction("Index");
                        }

                        account.Credit = model.TypeGuid == Codes.CreditorType ? account.Credit + cost : account.Credit - cost;
                        account.ModifiedDate = DateTime.Now;

                        var transactionBefore = context.Transaction
                            .Where(x => !x.IsDelete && x.ReceiptDate < PersianDateExtensionMethods.ToGeorgianDateTime(model.ReceiptDate))
                            .OrderByDescending(x => x.ReceiptDate)
                            .FirstOrDefault();

                        if (transactionBefore == null)
                        {
                            transaction.Credit = model.TypeGuid == Codes.CreditorType ? transaction.Credit + cost : transaction.Credit - cost;
                        }
                        else
                        {
                            transaction.Credit = model.TypeGuid == Codes.CreditorType ? transactionBefore.Credit + cost : transactionBefore.Credit - cost;
                        }

                        var transactionsAfter = context.Transaction
                            .Where(x => !x.IsDelete && x.ReceiptDate > PersianDateExtensionMethods.ToGeorgianDateTime(model.ReceiptDate))
                            .OrderBy(x => x.ReceiptDate)
                            .ToList();

                        if (transactionsAfter.Count > 0)
                        {
                            transactionsAfter[0].Credit = transactionsAfter[0].StateCodeGuid == Codes.PassedState ?
                                (transactionsAfter[0].TypeCodeGuid == Codes.CreditorType ? transaction.Credit + transactionsAfter[0].Cost : transaction.Credit - transactionsAfter[0].Cost) :
                                (transactionsAfter[0].Credit = transaction.Credit);

                            for (int i = 1; i < transactionsAfter.Count; i++)
                            {
                                transactionsAfter[i].Credit = transactionsAfter[i].StateCodeGuid == Codes.PassedState ?
                                    (transactionsAfter[i].TypeCodeGuid == Codes.CreditorType ? transactionsAfter[i - 1].Credit + transactionsAfter[i].Cost : transactionsAfter[i - 1].Credit - transactionsAfter[i].Cost) :
                                    (transactionsAfter[i].Credit = transactionsAfter[i - 1].Credit);
                            }
                        }
                    }
                    else
                    {
                        var transactionBefore = context.Transaction
                            .Where(x => !x.IsDelete && x.ReceiptDate < PersianDateExtensionMethods.ToGeorgianDateTime(model.ReceiptDate))
                            .OrderByDescending(x => x.ReceiptDate)
                            .FirstOrDefault();

                        transaction.Credit = transactionBefore == null ? 0 : transactionBefore.Credit;
                    }
                }

                context.Transaction.Add(transaction);

                if (Convert.ToBoolean(context.SaveChanges() > 0))
                {
                    TempData["ToasterState"] = ToasterState.Success;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.CreateTransactionSuccessful;
                }
                else
                {
                    TempData["ToasterState"] = ToasterState.Error;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.CreateTransactionFailed;
                }

                return RedirectToAction("Index");
            }

            return BadRequest();
        }

        [HttpGet]
        public IActionResult CreateCheckTransaction()
        {
            CodesRepository codeRepository = new CodesRepository(context);

            ViewBag.Accounts = new AccountsRepository(context).GetAccounts(userManager.GetUserId(User));
            ViewBag.TransactionTypes = codeRepository.GetCodesByCodeGroupGuid(CodeGroups.TransactionType);
            ViewBag.TransactionStates = codeRepository.GetCodesByCodeGroupGuid(CodeGroups.TransactionState);

            return View();
        }


        [HttpPost]
        public IActionResult CreateCheckTransaction(CreateCheckTransactionViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.AccountGuid = Constants.DefaultAccountGuid;
                long cost = Convert.ToInt64(model.Cost);

                Transaction transaction = new Transaction
                {
                    AccountGuid = model.AccountGuid,
                    TypeCodeGuid = model.TypeGuid,
                    StateCodeGuid = model.StateGuid,
                    Title = model.Title,
                    Cost = cost,
                    AccountSide = model.AccountSide,
                    Description = model.Description,
                    IsCheckTransaction = true,
                    ReceiptDate = PersianDateExtensionMethods.ToGeorgianDateTime(model.ReceiptDate)
                };

                CheckTransaction checkTransaction = new CheckTransaction
                {
                    Serial = model.Serial,
                    IssueDate = PersianDateExtensionMethods.ToGeorgianDateTime(model.IssueDate)
                };

                checkTransaction.Transaction = transaction;

                if (model.AccountGuid.HasValue)
                {
                    if (model.StateGuid == Codes.PassedState)
                    {
                        var account = context.Account
                            .Where(x => x.AccountGuid == model.AccountGuid)
                            .SingleOrDefault();

                        if (account == null)
                        {

AccountingSoftware/Views/Transactions/ChangeState.cshtml
@model ChangeTransactionStateViewModel

<form asp-controller="Transactions" asp-action="ChangeState" method="post">

    <input asp-for="Guid" type="hidden" />

    <div class="modal-main">

        <div class="form-group">
            <label asp-for="StateGuid" class="control-label"></label>
            <select asp-for="StateGuid" asp-items="ViewBag.TransactionStates" class="form-control Select2_Normal">
                <option></option>
            </select>
            <span asp-validation-for="StateGuid" class="text-danger"></span>
        </div>

    </div>

    <div>
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
    </div>

</form>

<script src="~/lib/jQuery.Select2/js/select2.js"></script>
<script src="~/lib/jQuery.Select2/js/i18n/fa.js"></script>
<script src="~/js/Select2_Config.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

AccountingSoftware/Views/Transactions/CreateAccountTransaction.cshtml
@model CreateAccountTransactionViewModel

@{
    ViewBag.Title = "افزودن تراکنش";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

@section Styles {
    <link href="~/lib/MdBootstrapPersianDateTimePickerMasterBs4/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
}

<div class="panel panel-body panel-default navigation">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>
</div>

<div class="panel form-body">
    <div class="panel-body">

        <form asp-controller="Transactions" asp-action="CreateAccountTransaction" method="post">

            <div class="modal-main">
                <div class="row" style="margin: 0 -30px;">

                    <div class="col-md-6">

                        @*<div class="form-group">
                            <label asp-for="AccountGuid" class="control-label"></label>
                            <select asp-for="AccountGuid" asp-items="ViewBag.Accounts" class="form-control Select2_Normal">
                                <option></option>
                            </select>
                            <span asp-validation-for="AccountGuid" class="text-danger"></span>
                        </div>*@

                        <div class="form-group">
                            <label asp-for="TypeGuid" class="control-label"></label>
                            <select asp-for="TypeGuid" asp-items="ViewBag.TransactionTypes" class="form-control Select2_Normal">
                                <option></option>
                            </select>
                            <span asp-validation-for="TypeGuid" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="StateGuid" class="control-label"></label>
                            <select asp-for="StateGuid" asp-items="ViewBag.TransactionStates" class="form-control Select2_Normal">
                                <option></option>
                            </select>
                            <span asp-validation-for="StateGuid" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Title" class="form-control" />
                            </div>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Cost" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Cost" class="form-control" type="text" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'prefix': '', 'placeholder': ''">
                            </div>
                            <span asp-validation-for="Cost" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="AccountSide" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="AccountSide" class="form-control" />
                            </div>
                            <span asp-validation-for="AccountSide" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Description" class="form-control" />
                            </div>
                        </div>

                    </div>

                    <div class="col-md-6">

                        <label asp-for="ReceiptDate" class="control-label"></label>
                        <div id="date"></div>
                        <input type="hidden" name="ReceiptDate" id="ReceiptDate" class="form-control">
                        <span asp-validation-for="ReceiptDate" class="text-danger"></span>

                    </div>

                </div>
            </div>

            <div style="margin-top: 20px;">
                <a href="@Url.Action("Index", "Transactions")" class="btn btn-danger modal-btn-Dual pull-left">انصراف</a>
                <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
            </div>

        </form>

    </div>
</div>

@section Scripts {

    <script src="~/lib/jQuery.Select2/js/select2.js"></script>
    <script src="~/lib/jQuery.Select2/js/i18n/fa.js"></script>
    <script src="~/js/Select2_Config.js"></script>

    <script src="~/lib/MdBootstrapPersianDateTimePickerMasterBs4/jquery.md.bootstrap.datetimepicker.js"></script>
    <script>
        $('#date').MdPersianDateTimePicker({
            targetTextSelector: '#ReceiptDate',
            textFormat: 'yyyy-MM-dd HH:mm:ss',
            inLine: true,
            enableTimePicker: false,
            englishNumber: true
        });
    </script>

    <script>
        $(document).ready(function () {
            // Initialize InputMask
            $(":input").inputmask();
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

AccountingSoftware/Views/Transactions/CreateCheckTransaction.cshtml
@model CreateCheckTransactionViewModel

@{
    ViewBag.Title = "افزودن تراکنش";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

@section Styles {
    <link href="~/lib/MdBootstrapPersianDateTimePickerMasterBs4/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
}

<div class="panel panel-body panel-default navigation">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>
</div>

<div class="panel form-body">
    <div class="panel-body">

        <form asp-controller="Transactions" asp-action="CreateCheckTransaction" method="post">

            <div class="modal-main">
                <div class="row" style="margin: 0 -30px;">

                    <div class="col-md-6">

                        <label asp-for="IssueDate" class="control-label"></label>
                        <div id="date1"></div>
                        <input type="hidden" name="IssueDate" id="IssueDate" class="form-control">
                        <span asp-validation-for="IssueDate" class="text-danger"></span>

                        <br />

                        @*<div class="form-group">
            <label asp-for="AccountGuid" class="control-label"></label>
            <select asp-for="AccountGuid" asp-items="ViewBag.Accounts" class="form-control Select2_Normal">
                <option></option>
            </select>
            <span asp-validation-for="AccountGuid" class="text-danger"></span>
        </div>*@

                        <div class="form-group">
                            <label asp-for="TypeGuid" class="control-label"></label>
                            <select asp-for="TypeGuid" asp-items="ViewBag.TransactionTypes" class="form-control Select2_Normal">
                                <option></option>
                            </select>
                            <span asp-validation-for="TypeGuid" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="StateGuid" class="control-label"></label>
                            <select asp-for="StateGuid" asp-items="ViewBag.TransactionStates" class="form-control Select2_Normal">
                                <option></option>
                            </select>
                            <span asp-validation-for="StateGuid" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Title" class="form-control" />
                            </div>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Description" class="form-control" />
                            </div>
                        </div>

                    </div>

                    <div class="col-md-6">

                        <label asp-for="ReceiptDate" class="control-label"></label>
                        <div id="date2"></div>
                        <input type="hidden" name="ReceiptDate" id="ReceiptDate" class="form-control">
                        <span asp-validation-for="ReceiptDate" class="text-danger"></span>

                        <br />

                        <div class="form-group">
                            <label asp-for="Cost" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Cost" class="form-control" type="text" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'prefix': '', 'placeholder': ''">
                            </div>
                            <span asp-validation-for="Cost" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="AccountSide" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="AccountSide" class="form-control" />
                            </div>
                            <span asp-validation-for="AccountSide" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Serial" class="control-label"></label>
                            <div class="input-group">
                                <span class=" input-group-addon">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                </span>
                                <input asp-for="Serial" class="form-control" />
                            </div>
                            <span asp-validation-for="Serial" class="text-danger"></span>
                        </div>

                    </div>

                </div>
            </div>

            <div style="margin-top: 20px;">
                <a href="@Url.Action("Index", "Transactions")" class="btn btn-danger modal-btn-Dual pull-left">انصراف</a>
                <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
            </div>

        </form>

    </div>
</div>

@section Scripts {

    <script src="~/lib/jQuery.Select2/js/select2.js"></script>
    <script src="~/lib/jQuery.Select2/js/i18n/fa.js"></script>
    <script src="~/js/Select2_Config.js"></script>

    <script src="~/lib/MdBootstrapPersianDateTimePickerMasterBs4/jquery.md.bootstrap.datetimepicker.js"></script>
    <script>
        $('#date1').MdPersianDateTimePicker({
            targetTextSelector: '#IssueDate',
            textFormat: 'yyyy-MM-dd HH:mm:ss',
            inLine: true,
            enableTimePicker: false,
            englishNumber: true,
            fromDate: true,
            groupId: 'date1-2-range'
        });
        $('#date2').MdPersianDateTimePicker({
            targetTextSelector: '#ReceiptDate',
            textFormat: 'yyyy-MM-dd HH:mm:ss',
            inLine: true,
            enableTimePicker: false,
            englishNumber: true,
            toDate: true,
            groupId: 'date1-2-range'
        });
    </script>

    <script>
        $(document).ready(function () {
            // Initialize InputMask
            $(":input").inputmask();
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

AccountingSoftware/Views/Transactions/Delete.cshtml
@model DeleteViewModel

<form asp-controller="Transactions" asp-action="Delete" method="post">

    <input asp-for="Guid" type="hidden" />

    <br />
    <h4 class="text-center">@Model.Message</h4>
    <br />

    <div>
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
    </div>
</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

AccountingSoftware/Views/Transactions/ShowCheckInfo.cshtml
@model CheckTransitionViewModel

<div id="Details-tabel">

    <div class="row userprofile-detiles-item" style="">
        <div class="col-md-3 userprofile-detiles-col-3-main">
            <div class="panel userprofile-detiles-col-3 ">
                <span class="userprofile-detiles-text">
                    @Html.DisplayNameFor(model => model.Serial)
                </span>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel userprofile-detiles-col-9">
                <span class="userprofile-detiles-text">
                    @Model.Serial
                </span>
            </div>
        </div>
    </div>

    <div class="row userprofile-detiles-item" style="">
        <div class="col-md-3 userprofile-detiles-col-3-main">
            <div class="panel userprofile-detiles-col-3 ">
                <span class="userprofile-detiles-text">
                    @Html.DisplayNameFor(model => model.IssueDate)
                </span>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel userprofile-detiles-col-9">
                <span class="userprofile-detiles-text">
                    @Model.IssueDate
                </span>
            </div>
        </div>
    </div>

</div>