AccountingSoftware/Models/Entities/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AccountingSoftware.Models.Entities
{
    public partial class Account
    {
        public Account()
        {
            Transaction = new HashSet<Transaction>();
        }


        [Key]
        public Guid AccountGuid { get; set; }

        [Required]
        public string UserGuid { get; set; }

        [StringLength(128)]
        public string BankName { get; set; }

        [StringLength(128)]
        public string AccountName { get; set; }

        [Required]
        [StringLength(128)]
        public string AccountNumber { get; set; }

        [StringLength(128)]
        public string CardNumber { get; set; }

        public long Credit { get; set; }

        public DateTime CreationDate { get; set; }

        public DateTime ModifiedDate { get; set; }

        public bool IsDelete { get; set; }


        [ForeignKey(nameof(UserGuid))]
        [InverseProperty(nameof(ApplicationUser.Account))]
        public virtual ApplicationUser User { get; set; }

        [InverseProperty("Account")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}

AccountingSoftware/Models/ViewModels/AccountViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.Models.ViewModels
{
    public class AccountViewModel
    {
        public Guid AccountGuid { get; set; }

        [Display(Name = "صاحب حساب")]
        public string UserFullName { get; set; }

        [Display(Name = "نام بانک")]
        public string BankName { get; set; }

        [Display(Name = "نوع حساب")]
        public string AccountName { get; set; }

        [Display(Name = "شماره حساب")]
        public string AccountNumber { get; set; }

        [Display(Name = "شماره کارت")]
        public string CardNumber { get; set; }

        [Display(Name = "اعتبار (تومان)")]
        public long Credit { get; set; }

        [Display(Name = "تاریخ آخرین ویرایش")]
        public string ModifiedDate { get; set; }
    }
}

AccountingSoftware/Models/ViewModels/DeleteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.Models.ViewModels
{
    public class DeleteViewModel
    {
        public Guid Guid { get; set; }

        public string Message { get; set; }
    }
}

AccountingSoftware/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingSoftware.Common;
using AccountingSoftware.Models;
using AccountingSoftware.Models.Entities;
using AccountingSoftware.Models.Enums;
using AccountingSoftware.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AccountingSoftware.Controllers
{
    public class AccountsController : Controller
    {
        private readonly AccountingSoftwareContext context;
        private readonly UserManager<ApplicationUser> userManager;

        public AccountsController(AccountingSoftwareContext context,
            UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var accounts = context.Account
                .Where(x => !x.IsDelete)
                .OrderByDescending(x => x.ModifiedDate)
                .Select(x => new AccountViewModel
                {
                    AccountGuid = x.AccountGuid,
                    UserFullName = x.User.FirstName + " " + x.User.LastName,
                    BankName = string.IsNullOrEmpty(x.BankName) ? Messages.NotSet : x.BankName,
                    AccountName = string.IsNullOrEmpty(x.AccountName) ? Messages.NotSet : x.AccountName,
                    AccountNumber = x.AccountNumber,
                    CardNumber = string.IsNullOrEmpty(x.CardNumber) ? Messages.NotSet : x.CardNumber,
                    Credit = x.Credit,
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(accounts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Create(CreateAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                Account account = new Account
                {
                    UserGuid = userManager.GetUserId(User),
                    BankName = model.BankName,
                    AccountName = model.AccountName,
                    AccountNumber = model.AccountNumber,
                    CardNumber = model.CardNumber,
                    Credit = Convert.ToInt64(model.Credit)
                };

                context.Account.Add(account);

                if (Convert.ToBoolean(context.SaveChanges()))
                {
                    TempData["ToasterState"] = ToasterState.Success;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.CreateAccountSuccessful;
                }
                else
                {
                    TempData["ToasterState"] = ToasterState.Error;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.CreateAccountFailed;
                }

                return RedirectToAction("Index");
            }

            return BadRequest();
        }

        [HttpGet]
        public IActionResult Edit(Guid accountGuid)
        {
            if (accountGuid == null)
            {
                return BadRequest();
            }

            var account = context.Account
                .Where(x => x.AccountGuid == accountGuid)
                .SingleOrDefault();

            if (account == null)
            {
                return NotFound();
            }

            EditAccountViewModel model = new EditAccountViewModel()
            {
                AccountGuid = account.AccountGuid,
                BankName = account.BankName,
                AccountName = account.AccountName,
                AccountNumber = account.AccountNumber,
                CardNumber = account.CardNumber,
                Credit = account.Credit.ToString()
            };

            return PartialView(model);
        }

        [HttpPost]
        public IActionResult Edit(EditAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                var account = context.Account
                    .Where(x => x.AccountGuid == model.AccountGuid)
                    .SingleOrDefault();

                if (account == null)
                {
                    NotFound();
                }

                account.BankName = model.BankName;
                account.AccountName = model.AccountName;
                account.AccountNumber = model.AccountNumber;
                account.CardNumber = model.CardNumber;
                account.Credit = Convert.ToInt64(model.Credit);
                account.ModifiedDate = DateTime.Now;

                if (Convert.ToBoolean(context.SaveChanges() > 0))
                {
                    TempData["ToasterState"] = ToasterState.Success;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.EditAccountSuccessful;
                }
                else
                {
                    TempData["ToasterState"] = ToasterState.Error;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.EditAccountFailed;
                }

                return RedirectToAction("Index");
            }

            return BadRequest();
        }

        [HttpGet]
        public IActionResult Delete(Guid accountGuid)
        {
            if (accountGuid == null)
            {
                return BadRequest();
            }

            var account = context.Account
                .Where(x => x.AccountGuid == accountGuid)
                .SingleOrDefault();

            if (account == null)
            {
                return NotFound();
            }

            DeleteViewModel model = new DeleteViewModel()
            {
                Guid = account.AccountGuid,
                Message = Messages.DeleteAccountText
            };

            return PartialView(model);
        }

        [HttpPost]
        public IActionResult Delete(DeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                var account = context.Account
                    .Where(x => x.AccountGuid == model.Guid)
                    .SingleOrDefault();

                if (account == null)
                {
                    NotFound();
                }

                account.IsDelete = true;

                if (Convert.ToBoolean(context.SaveChanges() > 0))
                {
                    TempData["ToasterState"] = ToasterState.Success;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.DeleteAccountSuccessful;
                }
                else
                {
                    TempData["ToasterState"] = ToasterState.Error;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.DeleteAccountFailed;
                }

                return RedirectToAction("Index");
            }

            return BadRequest();
        }
    }
}

AccountingSoftware/Views/Accounts/Create.cshtml
@model CreateAccountViewModel

    <form asp-controller="Accounts" asp-action="Create" method="post">
        <div class="modal-main">

            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <div class="input-group">
                    <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    <input asp-for="BankName" class="form-control" />
                </div>
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AccountName" class="control-label"></label>
                <div class="input-group">
                    <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    <input asp-for="AccountName" class="form-control" />
                </div>
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <div class="input-group">
                    <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    <input asp-for="AccountNumber" class="form-control" />
                </div>
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <div class="input-group">
                    <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    <input asp-for="CardNumber" class="form-control" />
                </div>
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Credit" class="control-label"></label>
                <div class="input-group">
                    <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    <input asp-for="Credit" class="form-control" value="0" type="text" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'prefix': '', 'placeholder': ''">
                </div>
                <span asp-validation-for="Credit" class="text-danger"></span>
            </div>

        </div>

        <div>
            <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
            <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
        </div>
    </form>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {
        // Initialize InputMask
        $(":input").inputmask();
    });
</script>

AccountingSoftware/Views/Accounts/Delete.cshtml
@model DeleteViewModel

<form asp-controller="Accounts" asp-action="Delete" method="post">

    <input asp-for="Guid" type="hidden" />

    <br />
    <h4 class="text-center">@Model.Message</h4>
    <br />

    <div>
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
    </div>
</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

AccountingSoftware/Views/Accounts/Edit.cshtml
@model EditAccountViewModel

<form asp-controller="Accounts" asp-action="Edit" method="post">
    
    <input asp-for="AccountGuid" type="hidden" />

    <div class="modal-main">

        <div class="form-group">
            <label asp-for="BankName" class="control-label"></label>
            <div class="input-group">
                <span class=" input-group-addon">
                    <i class="glyphicon glyphicon-pencil"></i>
                </span>
                <input asp-for="BankName" class="form-control" />
            </div>
            <span asp-validation-for="BankName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="AccountName" class="control-label"></label>
            <div class="input-group">
                <span class=" input-group-addon">
                    <i class="glyphicon glyphicon-pencil"></i>
                </span>
                <input asp-for="AccountName" class="form-control" />
            </div>
            <span asp-validation-for="AccountName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="AccountNumber" class="control-label"></label>
            <div class="input-group">
                <span class=" input-group-addon">
                    <i class="glyphicon glyphicon-pencil"></i>
                </span>
                <input asp-for="AccountNumber" class="form-control" />
            </div>
            <span asp-validation-for="AccountNumber" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CardNumber" class="control-label"></label>
            <div class="input-group">
                <span class=" input-group-addon">
                    <i class="glyphicon glyphicon-pencil"></i>
                </span>
                <input asp-for="CardNumber" class="form-control" />
            </div>
            <span asp-validation-for="CardNumber" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Credit" class="control-label"></label>
            <div class="input-group">
                <span class=" input-group-addon">
                    <i class="glyphicon glyphicon-pencil"></i>
                </span>
                <input asp-for="Credit" class="form-control" type="text" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'prefix': '', 'placeholder': ''">
            </div>
            <span asp-validation-for="Credit" class="text-danger"></span>
        </div>

    </div>

    <div>
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
    </div>
</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<script>
    $(document).ready(function () {
        // Initialize InputMask
        $(":input").inputmask();
    });
</script>

AccountingSoftware/Views/Accounts/Index.cshtml
@model IEnumerable<AccountViewModel>

@{
    ViewBag.Title = "حساب ها";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="panel panel-body panel-default navigation">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>

    <div class="pull-right">
        <a href="javascript:void(0)" onclick="Create()" data-toggle="tooltip" data-placement="auto" title="افزودن حساب">
            <i class="glyphicon glyphicon-plus navigation-btn-icon"></i>
        </a>
    </div>

</div>

<div class="panel panel-default">
    <div class="panel-body table-body" style="overflow-x: auto;">
        <table id="DateTable" class="table table-striped table-bordered" style="width: 100%">
            <thead>
                <tr class="table-tr">
                    <th scope="col">#</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.UserFullName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.BankName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.AccountName)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.AccountNumber)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.CardNumber)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.Credit)</th>
                    <th scope="col">@Html.DisplayNameFor(model => model.ModifiedDate)</th>
                    <th scope="col" data-orderable="false">کنترل</th>
                </tr>
            </thead>
            <tbody>

                @{
                    int x = 0;
                }

                @foreach (var item in Model)
                {
                    x++;

                    <tr>

                        <td scope="row">@x</td>

                        <td scope="row">
                            <span>@Html.DisplayFor(modelItem => item.UserFullName)</span>
                        </td>

                        <td scope="row">
                            <span>@Html.DisplayFor(modelItem => item.BankName)</span>
                        </td>

                        <td scope="row">
                            <span>@Html.DisplayFor(modelItem => item.AccountName)</span>
                        </td>

                        <td scope="row">
                            <span>@Html.DisplayFor(modelItem => item.AccountNumber)</span>
                        </td>

                        <td scope="row">
                            <span>@Html.DisplayFor(modelItem => item.CardNumber)</span>
                        </td>

                        <td scope="row">
                            <span class="credit" data-inputmask="'alias': 'numeric', 'groupSeparator': ',', 'autoGroup': true, 'digits': 0, 'digitsOptional': false, 'prefix': '', 'placeholder': ''">@Html.DisplayFor(modelItem => item.Credit)</span>
                        </td>

                        <td scope="row">
                            <span>@Html.DisplayFor(modelItem => item.ModifiedDate)</span>
                        </td>

                        <td scope="row">
                            <a class="control btn btn-warning btn-sm glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="auto" title="ویرایش" href="javascript:void(0)" onclick="Edit('@item.AccountGuid')"></a>
                            <a class="control btn btn-danger btn-sm glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="auto" title="حذف" href="javascript:void(0)" onclick="Delete('@item.AccountGuid')"></a>
                        </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

@section Modals {

    <script>

        function Create() {
            $.ajax({
                url: "/Accounts/Create",
                type: "Get",
                data: {}
            }).done(function (result) {
                $("#myModal").modal("show");
                $("#myModalLabel").html("افزودن حساب");
                $("#myModalBody").html(result);
            });
        }

        function Edit(accountGuid) {
            $.ajax({
                url: "/Accounts/Edit/?accountGuid=" + accountGuid,
                type: "Get",
                data: {}
            }).done(function (result) {
                $("#myModal").modal("show");
                $("#myModalLabel").html("ویرایش حساب");
                $("#myModalBody").html(result);
            });
        }

        function Delete(accountGuid) {
            $.ajax({
                url: "/Accounts/Delete/?accountGuid=" + accountGuid,
                type: "Get",
                data: {}
            }).done(function (result) {
                $("#myModal").modal("show");
                $("#myModalLabel").html("حذف حساب");
                $("#myModalBody").html(result);
            });
        }

    </script>

    <script>
        $(document).ready(function () {
            // Initialize InputMask
            $(".credit").inputmask();
        });
    </script>

}