AccountingSoftware/Models/Enums/Toaster.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.Models.Enums
{
    public enum ToasterType
    {
        Full,
        Title,
        Message
    }

    public enum ToasterState
    {
        Success,
        Info,
        Warning,
        Error
    }
}

AccountingSoftware/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AccountingSoftware.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AccountingSoftware/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingSoftware.Common;
using AccountingSoftware.Models;
using AccountingSoftware.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AccountingSoftware.Controllers
{
    public class ReportsController : Controller
    {
        private readonly AccountingSoftwareContext context;

        public ReportsController(AccountingSoftwareContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Remindings()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.ReceiptDate > DateTime.Now && x.ReceiptDate < DateTime.Now.AddDays(10) && x.StateCodeGuid == Codes.WaitingState)
                .OrderByDescending(x => x.ReceiptDate)
                .Select(x => new TransactionViewModel
                {
                    TransactionGuid = x.TransactionGuid,
                    AccountNumber = string.IsNullOrEmpty(x.Account.AccountNumber) ? Messages.NotSet : x.Account.AccountNumber,
                    Type = x.TypeCode.DisplayValue,
                    State = x.StateCode.DisplayValue,
                    Cost = x.Cost,
                    AccountSide = x.AccountSide,
                    Description = string.IsNullOrEmpty(x.Description) ? Messages.NotSet : x.Description,
                    IsCheckTransaction = x.IsCheckTransaction,
                    ReceiptDate = PersianDateExtensionMethods.ToPeString(x.ReceiptDate, "yyyy/MM/dd"),
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(transactions);
        }

        [HttpGet]
        public IActionResult PassedEvents()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.ReceiptDate < DateTime.Now && x.StateCodeGuid == Codes.WaitingState)
                .OrderByDescending(x => x.ReceiptDate)
                .Select(x => new TransactionViewModel
                {
                    TransactionGuid = x.TransactionGuid,
                    AccountNumber = string.IsNullOrEmpty(x.Account.AccountNumber) ? Messages.NotSet : x.Account.AccountNumber,
                    Type = x.TypeCode.DisplayValue,
                    State = x.StateCode.DisplayValue,
                    Cost = x.Cost,
                    AccountSide = x.AccountSide,
                    Description = string.IsNullOrEmpty(x.Description) ? Messages.NotSet : x.Description,
                    IsCheckTransaction = x.IsCheckTransaction,
                    ReceiptDate = PersianDateExtensionMethods.ToPeString(x.ReceiptDate, "yyyy/MM/dd"),
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(transactions);
        }

        [HttpGet]
        public IActionResult PassedStateTransactions()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.StateCodeGuid == Codes.PassedState)
                .OrderByDescending(x => x.ReceiptDate)
                .Select(x => new TransactionViewModel
                {
                    TransactionGuid = x.TransactionGuid,
                    AccountNumber = string.IsNullOrEmpty(x.Account.AccountNumber) ? Messages.NotSet : x.Account.AccountNumber,
                    Type = x.TypeCode.DisplayValue,
                    State = x.StateCode.DisplayValue,
                    Cost = x.Cost,
                    AccountSide = x.AccountSide,
                    Description = string.IsNullOrEmpty(x.Description) ? Messages.NotSet : x.Description,
                    IsCheckTransaction = x.IsCheckTransaction,
                    ReceiptDate = PersianDateExtensionMethods.ToPeString(x.ReceiptDate, "yyyy/MM/dd"),
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(transactions);
        }

        [HttpGet]
        public IActionResult NotPassedStateTransactions()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.StateCodeGuid == Codes.NotPassedState)
                .OrderByDescending(x => x.ReceiptDate)
                .Select(x => new TransactionViewModel
                {
                    TransactionGuid = x.TransactionGuid,
                    AccountNumber = string.IsNullOrEmpty(x.Account.AccountNumber) ? Messages.NotSet : x.Account.AccountNumber,
                    Type = x.TypeCode.DisplayValue,
                    State = x.StateCode.DisplayValue,
                    Cost = x.Cost,
                    AccountSide = x.AccountSide,
                    Description = string.IsNullOrEmpty(x.Description) ? Messages.NotSet : x.Description,
                    IsCheckTransaction = x.IsCheckTransaction,
                    ReceiptDate = PersianDateExtensionMethods.ToPeString(x.ReceiptDate, "yyyy/MM/dd"),
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(transactions);
        }

        [HttpGet]
        public IActionResult WaitingStateTransactions()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.StateCodeGuid == Codes.WaitingState)
                .OrderByDescending(x => x.ReceiptDate)
                .Select(x => new TransactionViewModel
                {
                    TransactionGuid = x.TransactionGuid,
                    AccountNumber = string.IsNullOrEmpty(x.Account.AccountNumber) ? Messages.NotSet : x.Account.AccountNumber,
                    Type = x.TypeCode.DisplayValue,
                    State = x.StateCode.DisplayValue,
                    Cost = x.Cost,
                    AccountSide = x.AccountSide,
                    Description = string.IsNullOrEmpty(x.Description) ? Messages.NotSet : x.Description,
                    IsCheckTransaction = x.IsCheckTransaction,
                    ReceiptDate = PersianDateExtensionMethods.ToPeString(x.ReceiptDate, "yyyy/MM/dd"),
                    ModifiedDate = PersianDateExtensionMethods.ToPeString(x.ModifiedDate, "yyyy/MM/dd HH:mm")

                }).ToList();

            return View(transactions);
        }
    }
}

AccountingSoftware/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingSoftware.Common;
using AccountingSoftware.Models.Entities;
using AccountingSoftware.Models.Enums;
using AccountingSoftware.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AccountingSoftware.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public UsersController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Dashboard");
            }

            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Username,
                    model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }

                    TempData["ToasterState"] = ToasterState.Info;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.LoginSuccessful;

                    return RedirectToAction("Index", "Dashboard");
                }

                TempData["ToasterState"] = ToasterState.Error;
                TempData["ToasterType"] = ToasterType.Message;
                TempData["ToasterMessage"] = Messages.LoginFailed;

                return RedirectToAction("Login");
            }

            return BadRequest();
        }

        //[AllowAnonymous]
        //[HttpGet]
        //public IActionResult Register()
        //{
        //    return View();
        //}

        //[AllowAnonymous]
        //[HttpPost]
        //public async Task<IActionResult> Register(RegisterViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var user = new ApplicationUser
        //        {
        //            UserName = model.Username,
        //            FirstName = model.FirstName,
        //            LastName = model.LastName,
        //            NationalCode = model.NationalCode,
        //            Address = model.Address
        //        };

        //        var result = await userManager.CreateAsync(user, model.Password);

        //        if (result.Succeeded)
        //        {
        //            await signInManager.SignInAsync(user, false);
        //            return RedirectToAction("Index", "Dashboard");
        //        }

        //        foreach (var error in result.Errors)
        //        {
        //            ModelState.AddModelError(string.Empty, error.Description);
        //        }
        //    }

        //    return View(model);
        //}

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(User);

                if (user == null)
                {
                    return RedirectToAction("Login");
                }

                var result = await userManager.ChangePasswordAsync(user,
                    model.CurrentPassword, model.NewPassword);

                if (!result.Succeeded)
                {
                    //foreach (var error in result.Errors)
                    //{
                    //    ModelState.AddModelError(string.Empty, error.Description);
                    //}

                    TempData["ToasterState"] = ToasterState.Error;
                    TempData["ToasterType"] = ToasterType.Message;
                    TempData["ToasterMessage"] = Messages.ChangePasswordFailed;

                    return RedirectToAction("Index", "Dashboard");
                }

                await signInManager.SignOutAsync();

                TempData["ToasterState"] = ToasterState.Success;
                TempData["ToasterType"] = ToasterType.Message;
                TempData["ToasterMessage"] = Messages.ChangePasswordSuccessful;

                return RedirectToAction("Login");
            }

            return BadRequest();
        }
    }
}

AccountingSoftware/ViewComponents/PassedEventsNotificationViewComponent.cs
using AccountingSoftware.Common;
using AccountingSoftware.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.ViewComponents
{
    public class PassedEventsNotificationViewComponent : ViewComponent
    {
        private readonly AccountingSoftwareContext context;

        public PassedEventsNotificationViewComponent(AccountingSoftwareContext context)
        {
            this.context = context;
        }

        public IViewComponentResult Invoke()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.ReceiptDate < DateTime.Now && x.StateCodeGuid == Codes.WaitingState)
                .ToList();

            return View(transactions.Count);
        }
    }
}

AccountingSoftware/ViewComponents/RemindingsNotificationViewComponent.cs
using AccountingSoftware.Common;
using AccountingSoftware.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.ViewComponents
{
    public class RemindingsNotificationViewComponent : ViewComponent
    {
        private readonly AccountingSoftwareContext context;

        public RemindingsNotificationViewComponent(AccountingSoftwareContext context)
        {
            this.context = context;
        }

        public IViewComponentResult Invoke()
        {
            var transactions = context.Transaction
                .Where(x => !x.IsDelete && x.ReceiptDate > DateTime.Now && x.ReceiptDate < DateTime.Now.AddDays(10) && x.StateCodeGuid == Codes.WaitingState)
                .ToList();

            return View(transactions.Count);
        }
    }
}

AccountingSoftware/Views/Shared/_AsideAdmin.cshtml
<ul class="navbar nav aside-panel">

    <li>
        <img src="~/Images/calc.png" alt="Logo" class="img-responsive img-rounded img-logo" style="height: 200px;">
        <a href="@Url.Action("Index", "Dashboard")">
            <i class="glyphicon glyphicon-dashboard"></i>
            داشبورد
        </a>
    </li>

    <li data-toggle="collapse" data-target="#sub-transactions">

        <a href="javascript:void(0)">
            <i class="glyphicon glyphicon-book"></i>
            مدیریت تراکنش ها
            <i class="glyphicon glyphicon-chevron-right pull-right gly-rotate-90"></i>
        </a>

        <ul class="collapse nav aside-sub-panel" id="sub-transactions">

            <li>
                <a href="@Url.Action("Index", "Transactions")">
                    <i class="glyphicon glyphicon-book"></i>
                    لیست تراکنش ها
                </a>
            </li>

            <li>
                <a href="@Url.Action("CreateAccountTransaction", "Transactions")">
                    <i class="glyphicon glyphicon-book"></i>
                    افزودن تراکنش حساب
                </a>
            </li>

            <li>
                <a href="@Url.Action("CreateCheckTransaction", "Transactions")">
                    <i class="glyphicon glyphicon-book"></i>
                    افزودن تراکنش چک
                </a>
            </li>

        </ul>

    </li>

    <li data-toggle="collapse" data-target="#sub-reports">

        <a href="javascript:void(0)">
            <i class="glyphicon glyphicon-book"></i>
            گزارشات
            <i class="glyphicon glyphicon-chevron-right pull-right gly-rotate-90"></i>
        </a>

        <ul class="collapse nav aside-sub-panel" id="sub-reports">

            <li>
                <a href="@Url.Action("Remindings", "Reports")">
                    <i class="glyphicon glyphicon-book"></i>
                    یاداوری ها
                </a>
            </li>

            <li>
                <a href="@Url.Action("PassedEvents", "Reports")">
                    <i class="glyphicon glyphicon-book"></i>
                    تراکنش های گذشته
                </a>
            </li>

            <li>
                <a href="@Url.Action("PassedStateTransactions", "Reports")">
                    <i class="glyphicon glyphicon-book"></i>
                    تراکنش های وصول شده
                </a>
            </li>

            <li>
                <a href="@Url.Action("NotPassedStateTransactions", "Reports")">
                    <i class="glyphicon glyphicon-book"></i>
                    تراکنش های وصول نشده
                </a>
            </li>

            <li>
                <a href="@Url.Action("WaitingStateTransactions", "Reports")">
                    <i class="glyphicon glyphicon-book"></i>
                    تراکنش های در انتظار وصول
                </a>
            </li>

        </ul>

    </li>

    <li>
        <a href="javascript::void(0)" onclick="ChangePassword()">
            <i class="glyphicon glyphicon-dashboard"></i>
            تغییر رمز عبور
        </a>
    </li>

</ul>

<script>

    function ChangePassword() {
        $.ajax({
            url: "/Users/ChangePassword",
            type: "Get",
            data: {}
        }).done(function (result) {
            console.log("test");
            $("#myModal").modal("show");
            $("#myModalLabel").html("تغییر رمز عبور");
            $("#myModalBody").html(result);
        });
    }

</script>

AccountingSoftware/Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>پنل کاربری | @ViewBag.Title</title>

    <link href="~/lib/Bootstarp/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Fonts/font awesome/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/css/font.css" rel="stylesheet" />

    <link href="~/css/site.css" rel="stylesheet" />

    <link href="~/lib/DataTables-1.10.18/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/jQuery.Select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/jQuery.Select2/css/select2-bootstrap.css" rel="stylesheet" />
    <link href="~/lib/jQuery.toastr/css/toastr.css" rel="stylesheet" />
    <link href="~/lib/MaterialDesignSwitch/MaterialDesignSwitch.css" rel="stylesheet" />

    @RenderSection("Styles", false)

</head>
<body>

    <header class="main-header container-fluid navbar-fixed-top">

        <div class="row">

            <div class="col-md-3 navHeader">
                <a href="@Url.Action("Index", "Home")" style="font-size: 14px;">نرم افزار حسابداری</a>
            </div>

            <nav class="col-md-9 navbar navbar-inverse" style="border-radius: 0;">
                <partial name="_Nav" />
            </nav>

        </div>

    </header>

    <main class="Main-Config">

        <aside class="aside-Config">
            <partial name="_AsideAdmin" />
        </aside>

        <section class="section-Config">
            @RenderBody()
        </section>

    </main>

    @*<footer></footer>*@

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" style="z-index: 1050;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div id="myModalBody"></div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/lib/Bootstarp/js/bootstrap.min.js"></script>
    <script src="~/lib/DataTables-1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/DataTables-1.10.18/js/dataTables.bootstrap.min.js"></script>
    <script src="~/lib/jQuery.Select2/js/select2.js"></script>
    <script src="~/lib/jQuery.Select2/js/i18n/fa.js"></script>
    <script src="~/lib/jQuery.toastr/js/toastr.min.js"></script>
    <script src="~/lib/jQuery.InputMask/jquery.inputmask.js"></script>

    <script src="~/js/Select2_Config.js"></script>
    <script src="~/js/Toastr_Config.js"></script>
    <script src="~/js/DataTables_Config.js"></script>

    <partial name="_Toaster" />

    @RenderSection("Scripts", false)

    @RenderSection("Modals", false)

    @*<script src="~/Scripts/modernizr-2.8.3.js"></script>*@

</body>
</html>

AccountingSoftware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccountingSoftware</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AccountingSoftware</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AccountingSoftware - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AccountingSoftware/Views/Shared/_Master.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>صفحه اصلی</title>

    <link href="~/lib/Bootstarp/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Fonts/font awesome/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/css/font.css" rel="stylesheet" />

    <link href="~/css/site.css" rel="stylesheet" />

    <link href="~/lib/DataTables-1.10.18/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/jQuery.Select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/jQuery.Select2/css/select2-bootstrap.css" rel="stylesheet" />
    <link href="~/lib/jQuery.toastr/css/toastr.css" rel="stylesheet" />
    <link href="~/lib/MaterialDesignSwitch/MaterialDesignSwitch.css" rel="stylesheet" />

    @RenderSection("Styles", false)

</head>
<body>

    <header class="main-header container-fluid navbar-fixed-top">

        <div class="row">

            <div class="col-md-3 navHeader">
                <a href="@Url.Action("Index", "Home")" style="font-size: 14px;">نرم افزار حسابداری</a>
            </div>

            <nav class="col-md-9 navbar navbar-inverse" style="border-radius: 0;">
                <partial name="_Nav" />
            </nav>

        </div>

    </header>

    <main style="padding: 75px 15px 0px 15px;">
        @RenderBody()
    </main>

    @*<footer></footer>*@

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" style="z-index: 1050;">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div id="myModalBody"></div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/lib/Bootstarp/js/bootstrap.min.js"></script>
    <script src="~/lib/DataTables-1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/DataTables-1.10.18/js/dataTables.bootstrap.min.js"></script>
    <script src="~/lib/jQuery.Select2/js/select2.js"></script>
    <script src="~/lib/jQuery.Select2/js/i18n/fa.js"></script>
    <script src="~/lib/jQuery.toastr/js/toastr.min.js"></script>
    <script src="~/lib/jQuery.InputMask/jquery.inputmask.js"></script>

    <script src="~/js/Select2_Config.js"></script>
    <script src="~/js/Toastr_Config.js"></script>
    <script src="~/js/DataTables_Config.js"></script>

    <partial name="_Toaster" />

    @RenderSection("Scripts", false)

    @RenderSection("Modals", false)

    @*<script src="~/Scripts/modernizr-2.8.3.js"></script>*@

</body>
</html>

AccountingSoftware/Views/Shared/_Nav.cshtml
@inject SignInManager<ApplicationUser> signInManager;
@inject UserManager<ApplicationUser> userManager;

@{
    if (signInManager.IsSignedIn(User))
    {
        string fullName = await new UsersRepository(userManager).GetUserFullName(User.Identity.Name);

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <vc:remindings-notification></vc:remindings-notification>
                <vc:passed-events-notification></vc:passed-events-notification>
                <li class="dropdown user user-menu menu-item">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-user nav-top-userInfo-icon"></i>
                        <span class="hidden-xs nav-username">@fullName</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="~/Images/person.png" width="85" class="img-circle" alt="User Image">
                            <p>
                                @fullName
                                <br />
                                <small>ادمین</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="@Url.Action("Index", "Dashboard")" class="btn btn-default btn-flat" @*style="width: 65px;"*@>پنل کاربری</a>
                            </div>
                            <div class="pull-right">
                                @*<a href="@Url.Action("Logout", "Account")" class="btn btn-default btn-flat" style="width:65px;">خروج</a>*@
                                <form method="post" asp-action="Logout" asp-controller="Users">
                                    <button type="submit" class="btn btn-default btn-flat" style="width: 65px;">خروج</button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    }
    else
    {
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu menu-item">
                    <a href="@Url.Action("Login", "Users")" class="">
                        <i class="glyphicon glyphicon-user nav-top-userInfo-icon"></i>
                        <span class="hidden-xs nav-username">ورود</span>
                    </a>
                </li>
            </ul>
        </div>
    }
}

AccountingSoftware/Views/Shared/_Toaster.cshtml
@using AccountingSoftware.Models.Enums

@{
    void Toast(string message, string title)
    {
        @switch ((ToasterState)TempData["ToasterState"])
        {
            case ToasterState.Success:

                <script>
                    ToastSuccess("@message", "@title");
                </script>

                break;

            case ToasterState.Info:

                <script>
                    ToastInfo("@message", "@title");
                </script>

                break;

            case ToasterState.Warning:

                <script>
                    ToastWarning("@message", "@title");
                </script>

                break;

            case ToasterState.Error:

                <script>
                    ToastError("@message", "@title");
                </script>

                break;

            default:
                break;
        }
    }

    if (TempData["ToasterState"] != null)
    {
        switch ((ToasterType)TempData["ToasterType"])
        {
            case ToasterType.Title:

                Toast(string.Empty, TempData["ToasterTitle"].ToString());
                break;

            case ToasterType.Full:

                Toast(TempData["ToasterMessage"].ToString(), TempData["ToasterTitle"].ToString());
                break;

            case ToasterType.Message:

                Toast(TempData["ToasterMessage"].ToString(), string.Empty);
                break;

            default:
                break;
        }

        TempData["ToasterState"] = null;
        TempData["ToasterType"] = null;
        TempData["ToasterTitle"] = null;
        TempData["ToasterMessage"] = null;
    }
}