AccountingSoftware/Models/ViewModels/CreateEventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingSoftware.Models.ViewModels
{
    public class CreateEventViewModel
    {
        [Display(Name = "نام رویداد")]
        public string EventTitle { get; set; }
    }
}

AccountingSoftware/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingSoftware.Common;
using AccountingSoftware.Models;
using AccountingSoftware.Models.Entities;
using AccountingSoftware.Models.Enums;
using AccountingSoftware.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AccountingSoftware.Controllers
{
    public class CalendarController : Controller
    {
        private readonly AccountingSoftwareContext _context;
        //private readonly Dictionary<string, string> _monthNumber = new Dictionary<string, string>()
        //{ 
        //    { "Jan", "01" },
        //    { "Feb", "02" },
        //    { "Mar", "03" },
        //    { "Apr", "04" },
        //    { "May", "05" },
        //    { "Jun", "06" },
        //    { "Jul", "07" },
        //    { "Aug", "08" },
        //    { "Sep", "09" },
        //    { "Oct", "10" },
        //    { "Nov", "11" },
        //    { "Dec", "12" },
        //};

        public CalendarController(AccountingSoftwareContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<JsonResult> GetEvents(string start, string end)
        {
            try
            {
                if (string.IsNullOrEmpty(start) || string.IsNullOrEmpty(end))
                    return Json(false);

                int startYear = Convert.ToInt32(start.Substring(0, 4));
                int startMonth = Convert.ToInt32(start.Substring(5, 2));
                int startDay = Convert.ToInt32(start.Substring(8, 2));

                DateTime startDate = new DateTime(startYear, startMonth, startDay).AddDays(1);

                int endYear = Convert.ToInt32(end.Substring(0, 4));
                int endMonth = Convert.ToInt32(end.Substring(5, 2));
                int endDay = Convert.ToInt32(end.Substring(8, 2));

                DateTime endDate = new DateTime(endYear, endMonth, endDay).AddDays(1);

                List<Transaction> transactions = await _context.Transaction
                    .Where(x => !x.IsDelete && x.StateCodeGuid == Codes.PassedState && x.ReceiptDate >= startDate & x.ReceiptDate < endDate)
                    .ToListAsync();

                List<DateTime> dates = new List<DateTime>();
                List<EventsViewModel> events = new List<EventsViewModel>();

                foreach (var transaction in transactions)
                {
                    List<Transaction> dateTransactions = transactions
                        .Where(x => !dates.Contains(x.ReceiptDate.Date) && x.ReceiptDate.Date == transaction.ReceiptDate.Date)
                        .OrderByDescending(x => x.ReceiptDate)
                        .ToList();

                    if (dateTransactions.Count <= 0)
                        continue;

                    EventsViewModel credit = new EventsViewModel()
                    {
                        Title = "موجودی: " + dateTransactions.First().Credit.ToString("#,0") + " تومان",
                        Start = transaction.ReceiptDate.ToString("yyyy-MM-dd")
                    };

                    EventsViewModel creditor = new EventsViewModel()
                    {
                        Title = "دریافتی: " + dateTransactions.Where(x => x.TypeCodeGuid == Codes.CreditorType).Sum(x => x.Cost).ToString("#,0") + " تومان",
                        Start = transaction.ReceiptDate.ToString("yyyy-MM-dd")
                    };

                    EventsViewModel debtor = new EventsViewModel()
                    {
                        Title = "پرداختی: " + dateTransactions.Where(x => x.TypeCodeGuid == Codes.DebtorType).Sum(x => x.Cost).ToString("#,0") + " تومان",
                        Start = transaction.ReceiptDate.ToString("yyyy-MM-dd")
                    };

                    events.AddRange(new List<EventsViewModel> { credit, creditor, debtor });

                    dates.Add(transaction.ReceiptDate.Date);
                }

                return Json(events);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        [HttpGet]
        public async Task<IActionResult> ShowCreditorDetails(string start)
        {
            try
            {
                if (string.IsNullOrEmpty(start))
                    return BadRequest();

                int startYear = Convert.ToInt32(start.Substring(0, 4));
                int startMonth = Convert.ToInt32(start.Substring(5, 2));
                int startDay = Convert.ToInt32(start.Substring(8, 2));

                DateTime startDate = new DateTime(startYear, startMonth, startDay).AddDays(1);

                List<CalendarEventDetailsViewModel> transactions = await _context.Transaction
                    .Where(x => !x.IsDelete && x.TypeCodeGuid == Codes.CreditorType && x.StateCodeGuid == Codes.PassedState && x.ReceiptDate >= startDate & x.ReceiptDate < startDate.AddDays(1))
                    .GroupBy(x => x.IsCheckTransaction)
                    .OrderBy(x => x.Key)
                    .Select(x => new CalendarEventDetailsViewModel()
                    {
                        TrasnactionType = x.Key ? "چک" : "حساب",
                        CostSum = x.Sum(x => x.Cost).ToString("#,0") + " تومان",

                    }).ToListAsync();

                return PartialView(transactions);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> ShowDebtorDetails(string start)
        {
            try
            {
                if (string.IsNullOrEmpty(start))
                    return BadRequest();

                int startYear = Convert.ToInt32(start.Substring(0, 4));
                int startMonth = Convert.ToInt32(start.Substring(5, 2));
                int startDay = Convert.ToInt32(start.Substring(8, 2));

                DateTime startDate = new DateTime(startYear, startMonth, startDay).AddDays(1);

                List<CalendarEventDetailsViewModel> transactions = await _context.Transaction
                    .Where(x => !x.IsDelete && x.TypeCodeGuid == Codes.DebtorType && x.StateCodeGuid == Codes.PassedState && x.ReceiptDate >= startDate & x.ReceiptDate < startDate.AddDays(1))
                    .GroupBy(x => x.IsCheckTransaction)
                    .OrderBy(x => x.Key)
                    .Select(x => new CalendarEventDetailsViewModel()
                    {
                        TrasnactionType = x.Key ? "چک" : "حساب",
                        CostSum = x.Sum(x => x.Cost).ToString("#,0") + " تومان",

                    }).ToListAsync();

                return PartialView(transactions);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //[HttpGet]
        //public IActionResult CreateEvent(string start, string end)
        //{
        //    TempData["start"] = start;
        //    TempData["end"] = end;

        //    return PartialView();
        //}

        //[HttpPost]
        //public async Task<IActionResult> CreateEvent(CreateEventViewModel model)
        //{
        //    try
        //    {
        //        if (!ModelState.IsValid)
        //            return BadRequest();

        //        string start = TempData["start"].ToString();
        //        string end = TempData["end"].ToString();

        //        if ((start == null || start == string.Empty) &&
        //            (end == null || end == string.Empty))
        //            return BadRequest();

        //        string startMonthName = start.Substring(4, 3);
        //        _monthNumber.TryGetValue(startMonthName, out string startMonthNum);

        //        string endMonthName = end.Substring(4, 3);
        //        _monthNumber.TryGetValue(endMonthName, out string endMonthNum);

        //        if (startMonthNum == null || endMonthNum == null)
        //            BadRequest();

        //        string startDay = start.Substring(8, 2);
        //        string startYear = start.Substring(11, 4);
        //        string startDate = startYear + '-' + startMonthNum + '-' + startDay;

        //        string endDay = end.Substring(8, 2);
        //        string endYear = end.Substring(11, 4);
        //        string endDate = endYear + '-' + endMonthNum + '-' + endDay;

        //        Calendar calendar = new Calendar()
        //        {
        //            Title = model.EventTitle,
        //            Start = startDate,
        //            End = endDate
        //        };

        //        _context.Calendar.Add(calendar);

        //        int res = await _context.SaveChangesAsync();

        //        if (Convert.ToBoolean(res))
        //        {
        //            TempData["ToasterState"] = ToasterState.Success;
        //            TempData["ToasterType"] = ToasterType.Message;
        //            TempData["ToasterMessage"] = Messages.CreateEventSuccessful;
        //        }
        //        else
        //        {
        //            TempData["ToasterState"] = ToasterState.Error;
        //            TempData["ToasterType"] = ToasterType.Message;
        //            TempData["ToasterMessage"] = Messages.CreateEventFailed;
        //        }

        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception)
        //    {
        //        TempData["ToasterState"] = ToasterState.Error;
        //        TempData["ToasterType"] = ToasterType.Message;
        //        TempData["ToasterMessage"] = Messages.CreateEventFailed;

        //        return RedirectToAction("Index");
        //    }
        //}

AccountingSoftware/Views/Calendar/CreateEvent.cshtml
@model CreateEventViewModel

<form asp-controller="Calendar" asp-action="CreateEvent" method="post">
    <div class="modal-main">

        <div class="form-group">
            <label asp-for="EventTitle" class="control-label"></label>
            <div class="input-group">
                <span class=" input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                <input asp-for="EventTitle" class="form-control" />
            </div>
            <span asp-validation-for="EventTitle" class="text-danger"></span>
        </div>

    </div>

    <div>
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
    </div>
</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

AccountingSoftware/Views/Calendar/DeleteEvent.cshtml
@model DeleteViewModel

<form asp-controller="Calendar" asp-action="DeleteEvent" method="post">

    <input asp-for="Guid" type="hidden" />

    <br />
    <h4 class="text-center">@Model.Message</h4>
    <br />

    <div>
        <button class="btn btn-danger modal-btn-Dual pull-left" type="button" data-dismiss="modal">انصراف</button>
        <button class="btn btn-success modal-btn-Dual pull-right" type="submit" name="btn-Delete">تایید</button>
    </div>
</form>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

AccountingSoftware/Views/Calendar/Index.cshtml
@{
    ViewBag.Title = "تقویم";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

<div class="panel panel-body panel-default navigation">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>

</div>

<div class="panel panel-default">
    <div class="panel-body" style="overflow-x: auto; color: #000000">
        <div id='calendar'></div>
    </div>
</div>

@section Styles {

    <link href="~/lib/fullcalendar-4.4.2/packages/core/main.css" rel="stylesheet" />
    <link href="~/lib/fullcalendar-4.4.2/packages/daygrid/main.css" rel="stylesheet" />
    <link href="~/lib/fullcalendar-4.4.2/packages/timegrid/main.css" rel="stylesheet" />
    <link href="~/lib/fullcalendar-4.4.2/packages/list/main.css" rel="stylesheet" />

}

@section Scripts {

    <script src="~/js/axios.min.js"></script>

    <script src="~/lib/fullcalendar-4.4.2/packages/core/main.js"></script>
    <script src="~/lib/fullcalendar-4.4.2/packages/core/locales-all.js"></script>
    <script src="~/lib/fullcalendar-4.4.2/packages/interaction/main.js"></script>
    <script src="~/lib/fullcalendar-4.4.2/packages/daygrid/main.js"></script>
    <script src="~/lib/fullcalendar-4.4.2/packages/timegrid/main.js"></script>
    <script src="~/lib/fullcalendar-4.4.2/packages/list/main.js"></script>

    <script>

        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'],
                header: {
                    left: 'next,prev today',
                    center: 'title',
                    right: 'dayGridMonth,dayGridWeek,dayGridDay, listMonth'
                },
                locale: 'fa',
                dir: 'rtl',
                weekNumbers: false,
                navLinks: true,
                selectable: true,
                select: function (arg) {
                    axios.get('Calendar/CreateEvent', {
                        params: {
                            start: arg.start,
                            end: arg.end
                        }
                    }).then(function (response) {
                        $('#myModal').modal('show');
                        $('#myModalLabel').html('افزودن رویداد');
                        $('#myModalBody').html(response.data);
                    }).catch(function (error) {
                        console.log(error);
                    })
                },
                windowResize: function (view) {
                    adjustSize(calendar);
                },
                editable: false,
                eventLimit: false,
                datesRender: function (info) {
                    axios.get('Calendar/GetEvents', {
                        params: {
                            start: info.view.currentStart,
                            end: info.view.currentEnd
                        }
                    }).then(function (response) {
                        var eventSources = calendar.getEventSources();
                        if (eventSources.length > 0) {
                            eventSources.forEach(function (eventSource) {
                                eventSource.remove();
                            });
                        }
                        calendar.addEventSource(response.data);
                    }).catch(function (error) {
                        console.log(error);
                    })
                },
                eventColor: '#222d32',
                eventBackgroundColor: '#222d32',
                eventBorderColor: '#222d32',
                eventRender: function (info) {
                    info.el.title = 'جهت حذف دو بار کلیک کنید';
                    info.el.style.transition = 'all 0.1s';
                    info.el.style.padding = '5px';
                    info.el.addEventListener('dblclick', function () {
                        $.ajax({
                            url: 'Calendar/DeleteEvent?eventGuid=' + info.event.id,
                            type: 'GET',
                        }).done(function (result) {
                            $('#myModal').modal('show');
                            $('#myModalLabel').html('حذف رویداد');
                            $('#myModalBody').html(result);
                        });
                    });
                },
                eventMouseEnter: function (info) {
                    if (calendar.view.type != 'listMonth') {
                        info.el.style.backgroundColor = 'red';
                        info.el.style.borderColor = 'red';
                    }
                },
                eventMouseLeave: function (info) {
                    if (calendar.view.type != 'listMonth') {
                        info.el.style.backgroundColor = '#222d32';
                        info.el.style.borderColor = '#222d32';
                    }
                }
            });

            calendar.render();

            adjustSize(calendar);
        });

        function adjustSize(calendar) {
            if (window.innerWidth <= 767) {
                calendar.setOption('header', {
                    left: 'next,prev today',
                    center: null,
                    right: 'title'
                });
                calendar.changeView('dayGridDay');
            } else {
                calendar.setOption('header', {
                    left: 'next,prev today',
                    center: 'title',
                    right: 'dayGridMonth,dayGridWeek,dayGridDay, listMonth'
                });
            }
        }

    </script>

}

AccountingSoftware/Views/Calendar/ShowCreditorDetails.cshtml
@model List<CalendarEventDetailsViewModel>

<div id="Details-tabel">

    @if (Model.Count <= 0)
    {
        <div class="row userprofile-detiles-item">
            <div class="col-12 text-center" style="padding: 5px 0px 15px 0px">
                جزییاتی یافت نشد
            </div>
        </div>
    }
    else
    {
        foreach (var item in Model)
        {
            <div class="row userprofile-detiles-item">
                <div class="col-md-3 userprofile-detiles-col-3-main">
                    <div class="panel userprofile-detiles-col-3 ">
                        <span class="userprofile-detiles-text">
                            @item.TrasnactionType
                        </span>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="panel userprofile-detiles-col-9">
                        <span class="userprofile-detiles-text">
                            @item.CostSum
                        </span>
                    </div>
                </div>
            </div>
        }
    }

</div>

AccountingSoftware/Views/Calendar/ShowDebtorDetails.cshtml
@model List<CalendarEventDetailsViewModel>

<div id="Details-tabel">

    @if (Model.Count <= 0)
    {
        <div class="row userprofile-detiles-item">
            <div class="col-12 text-center" style="padding: 5px 0px 15px 0px">
                جزییاتی یافت نشد
            </div>
        </div>
    }
    else
    {
        foreach (var item in Model)
        {
            <div class="row userprofile-detiles-item">
                <div class="col-md-3 userprofile-detiles-col-3-main">
                    <div class="panel userprofile-detiles-col-3 ">
                        <span class="userprofile-detiles-text">
                            @item.TrasnactionType
                        </span>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="panel userprofile-detiles-col-9">
                        <span class="userprofile-detiles-text">
                            @item.CostSum
                        </span>
                    </div>
                </div>
            </div>
        }
    }

</div>